# docker-compose.yml
version: '3'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    
  # Redis service
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Backend service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
      - ai
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/metapilot
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
      - AI_SERVICE_URL=http://ai:3001/api
    volumes:
      - ./backend:/app
      - /app/node_modules

  # AI service
  ai:
    build:
      context: ./ai
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - GAIA_API_KEY=${GAIA_API_KEY}
      - GAIA_API_URL=${GAIA_API_URL}
    volumes:
      - ./ai:/app
      - /app/node_modules

volumes:
  mongodb_data:
  redis_data: